name: Keycloak BFS

on:
  push:
    branches:
    - 'stshapir/*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KEYCLOAK_VERSION: 20.0.1
  DOCKER_NAMESPACE: verrazzano

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Get Keycloak image tag
      - name: Get image tag
        run: |
          TIME_STAMP=$(date +'%Y%m%d%H%M%S')
          SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "DOCKER_IMAGE_TAG=v${{env.KEYCLOAK_VERSION}}-$TIME_STAMP-$SHORT_COMMIT_SHA" >> "$GITHUB_ENV"
          echo "Image tag: $DOCKER_IMAGE_TAG"

      # Build Keycloak (Maven)
      - name: Build Keycloak distribution
        run : |
          cd quarkus
          mvn --settings ../maven-settings.xml -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests
          mvn --settings ../maven-settings.xml -f dist/pom.xml clean install

      # Copy additional licenses, etc.
      - name: Copy additional artifacts
        run: |
          cd quarkus
          cp ./dist/target/keycloak-${{env.KEYCLOAK_VERSION}}.tar.gz ./container
          cp ../THIRD_PARTY_LICENSES.txt ./container
          cp ../SECURITY.md ./container
          cp ../LICENSE.txt ./container
          cp ../README.md ./container

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./quarkus/container
          push: true
          tags: ${{env.REGISTRY}}/${{env.DOCKER_NAMESPACE}}/${{env.IMAGE_NAME}}:${{env.DOCKER_IMAGE_TAG}}
          file: Dockerfile_verrazzano
          build-args: KEYCLOAK_DIST=keycloak-${{env.KEYCLOAK_VERSION}}.tar.gz

      # Upload artifacts to GitHub
      - name: Store Keycloak artifacts
        id: store-keycloak
        uses: actions/upload-artifact@v3
        with:
          name: keycloak-artifacts.zip
          retention-days: 1
          path: |
            quarkus/container
            quarkus/container/**/*.tar.gz