# Copyright (c) 2023, Oracle Corporation and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Verrazzano GitHub Actions Keycloak BFS.
# ---------------------------------------------------------------------------

name: Keycloak BFS
run-name: GitHub Actions workflow triggered by changes to Keycloak BFS 🔑

on:
  push:
    branches:
      - 'oracle/release/*'
      - 'bfs/stshapir/*'
  workflow_dispatch:
    inputs:
      KEYCLOAK_VERSION:
        description: 'Keycloak version to build'
        required: true
        default: '20.0.1'

env:
  REGISTRY: ghcr.io
  KEYCLOAK_VERSION: github.event.inputs.KEYCLOAK_VERSION

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: debug keycloak conditional
        run: |
          echo ${{ env.KEYCLOAK_VERSION }}

      # Login against a Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Get short commit tag
      - name: Get short commit tag
        run: |
          echo "TIME_STAMP=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_ENV"
          echo "SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      # Override Keycloak version for main branches
      - name: Get Keycloak version (protected)
        if: github.ref_protected
        run: echo "KEYCLOAK_VERSION=$(echo ${{ github.ref_name }} | sed 's:.*/::')" >> "$GITHUB_ENV"

      # Get Keycloak image name for main branches
      - name: Get image name (protected)
        if: github.ref_protected
        run: echo "IMAGE_NAME=keycloak" >> "$GITHUB_ENV"

      # Get Keycloak image name for temp branches
      - name: Get image name (developer)
        if: ${{ !github.ref_protected }}
        run: echo "IMAGE_NAME=keycloak-temp" >> "$GITHUB_ENV"

      # Get Keycloak image tag
      - name: Get image tag
        run: echo "DOCKER_IMAGE_TAG=v${{ env.KEYCLOAK_VERSION }}-${{ env.TIME_STAMP }}-${{ env.SHORT_COMMIT_SHA }}" >> "$GITHUB_ENV"

      # ---------------------------------------------------------------------------
      # Keycloak <v20.0.1
      # ---------------------------------------------------------------------------

      - name: debug keycloak conditional
        run: |
          echo ${{ env.KEYCLOAK_VERSION }}

      # Build Keycloak (Maven) for <v20.0.1
      - name: Build Keycloak distribution (<v20.0.1)
        if: "env.KEYCLOAK_VERSION == '10.0.2' || env.KEYCLOAK_VERSION == '15.0.2'"
        run : |
          cd ${{github.workspace}}/quarkus
          mvn --settings ../maven-settings.xml -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests
          mvn --settings ../maven-settings.xml -f dist/pom.xml clean install

      # Copy additional licenses, etc. for <v20.0.1
      - name: Copy additional artifacts (<v20.0.1)
        if: env.KEYCLOAK_VERSION == '10.0.2' || env.KEYCLOAK_VERSION == '15.0.2'
        run: |
          cd ${{ github.workspace }}/quarkus
          cp ./dist/target/keycloak-${{ env.KEYCLOAK_VERSION }}.tar.gz ./container
          cp ../THIRD_PARTY_LICENSES.txt ./container
          cp ../SECURITY.md ./container
          cp ../LICENSE.txt ./container
          cp ../README.md ./container

      # Build and push Docker image for <v20.0.1
      - name: Build and push (<v20.0.1)
        if: env.KEYCLOAK_VERSION == '10.0.2' || env.KEYCLOAK_VERSION == '15.0.2'
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/quarkus/container
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          file: ${{ github.workspace }}/quarkus/container/Dockerfile_verrazzano
          build-args: KEYCLOAK_DIST=keycloak-${{ env.KEYCLOAK_VERSION }}.tar.gz

      # ---------------------------------------------------------------------------
      # Keycloak v20.0.1+
      # ---------------------------------------------------------------------------

      # Build Keycloak (Maven) for v20.0.1+
      - name: Build Keycloak distribution (v20.0.1+)
        if: ${{ env.KEYCLOAK_VERSION == '20.0.1' || env.KEYCLOAK_VERSION == '20.0.3' }}
        run : |
          echo "got here"
          cd ${{github.workspace}}/quarkus
          mvn --settings ../maven-settings.xml -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests
          mvn --settings ../maven-settings.xml -f dist/pom.xml clean install

      # Copy additional licenses, etc. for v20.0.1+
      - name: Copy additional artifacts (v20.0.1+)
        if: env.KEYCLOAK_VERSION == '20.0.1' || env.KEYCLOAK_VERSION == '20.0.3'
        run: |
          cd ${{ github.workspace }}/quarkus
          cp ./dist/target/keycloak-${{ env.KEYCLOAK_VERSION }}.tar.gz ./container
          cp ../THIRD_PARTY_LICENSES.txt ./container
          cp ../SECURITY.md ./container
          cp ../LICENSE.txt ./container
          cp ../README.md ./container

      # Build and push Docker image for v20.0.1+
      - name: Build and push (v20.0.1+)
        if: env.KEYCLOAK_VERSION == '20.0.1' || env.KEYCLOAK_VERSION == '20.0.3'
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/quarkus/container
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          file: ${{ github.workspace }}/quarkus/container/Dockerfile_verrazzano
          build-args: KEYCLOAK_DIST=keycloak-${{ env.KEYCLOAK_VERSION }}.tar.gz

      # Scan container image
